### ISSUE TITLE
Rule: Try to avoid using first-person plural like 'we'

### ISSUE THREAD

**Issue by dariavladykina** [dmpop/technically#13]
The rule "Try to avoid using first-person plural like 'we', etc." contradicts the DSG: When giving a recommendation, start with <quote>We recommend</quote>.
I would also consider it not too necessary for our tech writing, what do you think?

**Comment by dmpop** [comment]
Strongly disagree: who are _we_? We should be replaced with SUSE, or something like _it is recommended_.

**Comment by dariavladykina** [comment]
This has been discussed [before](https://github.com/SUSE/doc-styleguide/issues/59). The Stylewich committee have agreed on sticking with 'We recommend'. 'We' is meant as a collective of authors, the so-called 'editorial we'.

**Comment by dmpop** [comment]
Apart _we recommend_, are there any conceivable context, where _we_ is acceptable?

**Comment by dariavladykina** [comment]
Actually not. Maybe we can add an exception for 'We recommend'? Or just keep the warning and ignore it for this phrase.

**Comment by dmpop** [comment]
I'll think about it. :smile:
