### ISSUE TITLE
Filesystem Hierarchy Standard

### ISSUE THREAD

**Issue by dariavladykina** [dmpop/technically#15]
Can we add this term in [#117](https://github.com/SUSE/doc-styleguide/issues/117) to the spell-checker please?

**Comment by dmpop** [comment]
**Incorrect:** _File system Hierarchy Standard_, _Filesystem Hierarchy Standard_, _filesystem hierarchy standard_, _file system hierarchy standard_
**Correct:** _Filesystem Hierarchy Standard_

Is that what you mean?

**Comment by dariavladykina** [comment]
Exactly. Thanks!
