### ISSUE TITLE
En and em dash conflict

### ISSUE THREAD

**Issue by bryce-carson** [dmpop/technically#4]
The en and the em dash are typographically different. Depending on what the SUSE style guide indicates their usages should be, the rules contained in the [`EnDash.yml`](EnDash.yml) and [`EmDash.yml`](EmDash.yml) should be retitled and the message modified.

Typically an en dash is used to hyphenate words (where the ASCII `hyphen-minus` would be used), and em dashes are used with discretion as an alternative interruption marking (rather than parenthetical content, or content between commas).

🤷🏼

I was reading some of the rules and noticed that; I'm unfamiliar with the SUSE style guide. I just setup vale.sh with Emacs and whatnot. :)

Thanks for this blog post: https://www.suse.com/c/write-with-a-little-help-from-a-stylish-friend/

**Comment by dmpop** [comment]
Good point! I'll look into it. Thank you for filing an issue!
