### ISSUE TITLE
Rule: Word after colon must be in lowercase (does not fully correspond with SUSE Writer's Guide)

### ISSUE THREAD

**Issue by dariavladykina** [dmpop/technically#6]
The rule stating that the word after colon must be in lowercase does not fully correspond with SUSE Writer's Guide which says: 

"Capitalize the first word after a colon only if it is a proper noun or the start of a complete sentence: He promised this: The company will make good on all the losses. But: There were three considerations: expense, time and feasibility".

I would ask to adjust the Vale rule accordingly.

Thanks!

**Comment by dmpop** [comment]
The rule in the SUSE Writer's Guide describes a fringe-edge case. The "lowercase after colon" rule applies in 99.9% of cases.
